src = ['main.c', 'eos_test.c', 'port_test.c']

paths = ['.', '../../eventos', '../../3rd/unity']

defines = ['test']
ccflags = []

env = Environment()
env.Append(CPPDEFINES = defines)
env.Append(CCCOMSTR = "CC $SOURCES")
env.Append(CPPPATH=paths)

obj = env.Object(src)
 
Return('obj')