src = Glob('*.c')

paths = ['.', '../3rd/mdebug', '../examples/unittest/']

defines = ['eventos']
ccflags = []

env = Environment()
env.Append(CPPDEFINES = defines)
env.Append(CCCOMSTR = "CC $SOURCES")
env.Append(CPPPATH = paths)

obj = env.Object(src)
 
Return('obj')